name: Release Build

on:
  push:
    tags:
      - "v*.*.*"

env:
  PROJECT_PATH: QSolver.csproj
  CERTIFICATE_PATH: certificate.pfx

jobs:
  build:
    runs-on: windows-latest
    environment: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Decode certificate
        run: |
          $certBytes = [System.Convert]::FromBase64String("${{ secrets.SIGNING_CERTIFICATE }}")
          $certPath = Join-Path -Path $env:RUNNER_TEMP -ChildPath $env:CERTIFICATE_PATH
          [System.IO.File]::WriteAllBytes($certPath, $certBytes)
        shell: pwsh

      - name: Build and Publish
        run: |
          dotnet publish ${{ env.PROJECT_PATH }} `
            --configuration Release `
            --runtime win-x64 `
            --self-contained true `
            --output ./publish `
            -p:PublishSingleFile=true `
            -p:IncludeNativeLibrariesForSelfExtract=true `
            -p:EnableCompressionInSingleFile=true
        shell: pwsh

      - name: Sign executable
        run: |
          $certPath = Join-Path -Path $env:RUNNER_TEMP -ChildPath $env:CERTIFICATE_PATH
          $signtool = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\signtool.exe"
          & $signtool sign /f $certPath /p "${{ secrets.CERTIFICATE_PASSWORD }}" /tr http://timestamp.digicert.com /td sha256 /fd sha256 ./publish/QSolver.exe
        shell: pwsh

      - name: Create ZIP archive
        run: Compress-Archive -Path ./publish/* -DestinationPath ./QSolver.zip
        shell: pwsh

      - name: Delete certificate
        run: Remove-Item -Path (Join-Path -Path $env:RUNNER_TEMP -ChildPath $env:CERTIFICATE_PATH) -Force
        shell: pwsh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./QSolver.zip
            ./publish/QSolver.exe
          body: |
            ## QSolver ${{ github.ref_name }}

            ### New Features and Improvements
            - ✨ Enhanced Question Editor
              - Advanced editor with text format preservation
              - Larger editing window
              - Improved text processing
            - 🎨 Modern UI Updates
              - Dark theme enhancements
              - Rounded corner design
              - Smooth transition animations
            - 🔧 API Key Management
              - Easy key addition/editing
              - Secure key storage
            - 📝 Solution Steps Viewer
              - Detailed solution explanations
              - Step-by-step solution display

            ### Technical Improvements
            - 🔒 Digitally signed application
            - 📦 Self-contained single-file executable
            - 🚀 Performance optimizations

            ### Installation
            1. Download and extract the ZIP file to your preferred location
            2. Run `QSolver.exe`

            ### Requirements
            - Windows 10 or later
            - .NET 8.0 Runtime (not required as this is a self-contained build)

            ### Note
            This release includes significant features and improvements. If you encounter any issues, please report them in the Issues section.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
